### ISSUE TITLE
Move all related global variables for peer-to-peer communication to the Network class

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-rust#331]
## Acceptance Criteria
- [x] All Peer-to-peer variables used by the network are in the network class
- [x] Passed all test cases.

## Subtasks

- [x] `PEERS_DB_GLOBAL` & its usage
- [x] `PEERS_REQUEST_RESPONSES_GLOBAL` & its usage
- [x] `PEERS_REQUEST_WAKERS_GLOBAL` & its usage
- [x] `INBOUND_PEER_CONNECTIONS_GLOBAL` & its usage
- [x] `OUTBOUND_PEER_CONNECTIONS_GLOBAL` & its usage
- [x] Retest all test cases.
- [x] Review and signoff of task completion
